name = "patch_test8"
mesh = "../../examples/ch02/PatchTest8.dat"
element_type = "SmallStrainContinuum"
material_type = "PlaneStress"
solver_type = "LinearSolver"
element_group = "ContElem"

[material]
E = 1.0e6
nu = 0.25
