name = "patch_test8_plane_strain"
mesh = "../../examples/ch02/PatchTest8.dat"
element_type = "SmallStrainContinuum"
material_type = "PlaneStrain"
solver_type = "LinearSolver"
element_group = "ContElem"

[material]
E = 1.0e6
nu = 0.25
